sudo: false
language: node_js
node_js:
- node
- 8.4.0
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: AjXiJ0ZCImqCQaqBamRCZTq6ZDrfPOzbBa5ahBy7tB+0s6WDbOnULSOfPQh12e2Es53PDz5DIAYgQkXRdsIAbCim/jz0mfSEK8mOpzUOCGRHUpHk5qhHPIK8F//6BlHLW9BmUSOJbqnxj6Pa483FM2Eri9i+o0WkoCCGzq87a3lhLQXghj73SdgJ/gMI3f7YLS2Px/AnI/feOWacZPJT23ffahWGyVJ4xx9EI0OjDST/izNxUjGqgyLq6aVkFjfb1UI/NXmRXFkHrjCvZ6hHO66bjKgCm+t2U5mvz6t54+4FiBS5fV45a+xaRXrPnuyaTsuWXw0r+uCmEudGeJ/r+O1uFyQ0FnGFrRZtYJmOaFni+lugbroB1TBteJ/5Ae5RnsybPpcpdtobtrr70lOKHXpI9QC3hnndeRIqMejWIQL2mGwwS9dpjZZ3I6VlMIX4LkfMNxleSiXw4UVhm25trcPDpZm9ng+6p5BqDABW1sOBInmphmtQ8+JzALpv7wjt9LhGiSSX4QFVtNy95/kt2mUZ7vqtj/s02GVfvapMnf3wPwuU4oKxJI9XWAHAHYY6WMDbHL/i+dI5YOxF53Rnj8WjTzGh78RYfptsxHw63bVB+9BMRUjQqhrLiohM2Is7yNyOuaYO5kf20r/LMqnTN/n2aFlv0JKp2MizAxde8yE=
script: npm run test npm run start
