sudo: false
language: node_js
node_js:
- node
- 8.4.0
cache:
  directories:
  - node_modules
script:
- npm run test
- npm run build
jobs:
  include:
    - stage: deploy to staging
      script: skip
      deploy: &heroku
        provider: heroku
        app: still-inlet-21388
        api_key:
            secure: $HEROKU_AUTH_TOKEN
        on:
            repo: https://github.com/Udobnaja/lesson-4-5
    - stage: deploy to production
      script: skip
      deploy:
        <<: *heroku
        app: git-log-production